// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// c_seglengths
NumericVector c_seglengths(const List& sl, const NumericVector& x, const NumericVector& y, const NumericVector& z);
RcppExport SEXP _natcpp_c_seglengths(SEXP slSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type sl(slSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(c_seglengths(sl, x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// c_total_cable_sl
double c_total_cable_sl(const List& sl, const NumericVector& x, const NumericVector& y, const NumericVector& z);
RcppExport SEXP _natcpp_c_total_cable_sl(SEXP slSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type sl(slSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(c_total_cable_sl(sl, x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// c_listlengths
IntegerVector c_listlengths(const List& L);
RcppExport SEXP _natcpp_c_listlengths(SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(c_listlengths(L));
    return rcpp_result_gen;
END_RCPP
}
// c_topntail
IntegerMatrix c_topntail(const List& L);
RcppExport SEXP _natcpp_c_topntail(SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(c_topntail(L));
    return rcpp_result_gen;
END_RCPP
}
// c_EdgeListFromSegList
IntegerMatrix c_EdgeListFromSegList(const List& L);
RcppExport SEXP _natcpp_c_EdgeListFromSegList(SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(c_EdgeListFromSegList(L));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_natcpp_c_seglengths", (DL_FUNC) &_natcpp_c_seglengths, 4},
    {"_natcpp_c_total_cable_sl", (DL_FUNC) &_natcpp_c_total_cable_sl, 4},
    {"_natcpp_c_listlengths", (DL_FUNC) &_natcpp_c_listlengths, 1},
    {"_natcpp_c_topntail", (DL_FUNC) &_natcpp_c_topntail, 1},
    {"_natcpp_c_EdgeListFromSegList", (DL_FUNC) &_natcpp_c_EdgeListFromSegList, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_natcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
