# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_seglengths <- function(sl, x, y, z) {
    .Call(`_natcpp_c_seglengths`, sl, x, y, z)
}

c_total_cable_sl <- function(sl, x, y, z) {
    .Call(`_natcpp_c_total_cable_sl`, sl, x, y, z)
}

c_listlengths <- function(L) {
    .Call(`_natcpp_c_listlengths`, L)
}

c_topntail <- function(L) {
    .Call(`_natcpp_c_topntail`, L)
}

c_EdgeListFromSegList <- function(L) {
    .Call(`_natcpp_c_EdgeListFromSegList`, L)
}

